### ISSUE TITLE
关于中国象棋NNUE的训练过程和参数

### ISSUE THREAD

**Issue by shuangqiao999** [PikaCat-OuO/ChineseChess#1]
你好 我们正在为变体仙女鱼象棋训练nnue文件 在空白基础上跑谱 经过多次迭代 已经很接近官方发布的文件了 但没有超越官方的nnue 可能我们的训练方法没有达到最佳状态 希望你能加入到群里 给予指导和帮助 qq群：615587792

**Comment by PikaCat-OuO** [comment]
“变体仙女鱼象棋” “没有达到最佳状态” 看起来一股机翻味啊 XD
其实我不是什么深度学习专家，所以可能并不能给予你们什么有价值的指导和帮助，另外由于隐私的缘故，我就不加群了，但是我可以说一下我目前正在实施的训练方法与我认为最佳的训练方法。

#### 目前我正在实施的训练方法（我的机器性能不佳，只能这样处理）：
使用数据生成器生成数据，具体的参数设置为深度9层，使用纯NNUE的方式评分，使用最新的中国象棋NNUE神经网络（也就是[Belzedar94](https://github.com/Belzedar94)的那个网络），生成10M的数据作为训练集，额外生成1M的数据作为验证集。
```bash
uci
setoption name Use NNUE value pure
setoption name EvalFile value xiangqi.nnue
setoption name Threads value 8
setoption name Hash value 2048
setoption name UCI_Variant value xiangqi
isready
generate_training_data depth 9 count 10000000 random_multi_pv 4 random_multi_pv_diff 100 random_move_count 8 random_move_max_ply 20 write_min_ply 5 eval_limit 10000 set_recommended_uci_options data_format bin output_file_name xiangqi.bin
generate_training_data depth 9 count 1000000 random_multi_pv 4 random_multi_pv_diff 100 random_move_count 8 random_move_max_ply 20 write_min_ply 5 eval_limit 10000 set_recommended_uci_options data_format bin output_file_name xiangqi-validate.bin
quit
```
接着，将数据上传到Google Colab，不同于你们从头开始训练，我将最新的NNUE文件转换为.pt文件，然后接着在上面进行训练，按照官方的说法，训练400个epoch足以。
```bash
%cd /content/drive/MyDrive/variant-nnue-pytorch
!pip install pytorch_lightning
!python serialize.py --features='HalfKAv2' xiangqi.nnue startingpointfortraining.pt
!python train.py --resume-from-model startingpointfortraining.pt --threads 1 --num-workers 1 --gpus 1 --max_epochs 400 xiangqi.bin xiangqi-validate.bin
!python serialize.py logs/default/version_0/checkpoints/last.ckpt xiangqi.nnue
```
最后，用variantfishtest进行测试就可以了。

#### 我认为的最佳的训练方式（相比于上面的方式，只需要作出两处更改）：
一是在数据生成时不使用NNUE网络进行评分，采用原来的非NNUE方式进行评分，然后设置深度为20层，生成1B的数据作为训练集，生成100M的数据作为测试集。具体操作如下：
```bash
uci
setoption name Use NNUE value false
setoption name Threads value 8
setoption name Hash value 2048
setoption name UCI_Variant value your_variant
isready
generate_training_data depth 20 count 1000000000 random_multi_pv 4 random_multi_pv_diff 100 random_move_count 8 random_move_max_ply 20 write_min_ply 5 eval_limit 10000 set_recommended_uci_options data_format bin output_file_name xiangqi.bin
generate_training_data depth 20 count 100000000 random_multi_pv 4 random_multi_pv_diff 100 random_move_count 8 random_move_max_ply 20 write_min_ply 5 eval_limit 10000 set_recommended_uci_options data_format bin output_file_name xiangqi-validate.bin
quit
```
二是在训练时不从最新的NNUE网络上继续训练，而是从头开始训练（空白文件开始训练）。
```bash
%cd /content/drive/MyDrive/variant-nnue-pytorch
!pip install pytorch_lightning
!python train.py --threads 1 --num-workers 1 --gpus 1 --max_epochs 400 xiangqi.bin xiangqi-validate.bin
!python serialize.py logs/default/version_0/checkpoints/last.ckpt xiangqi.nnue
```
但是碍于硬件的限制，这个想法很难实现。

至于更多的指导意见，建议你们咨询[Belzedar94](https://github.com/Belzedar94)，他训练了一堆网络，应该在这方面挺屌的。

**Comment by shuangqiao999** [comment]
谢谢你的指导 我会把这些建议反馈到群里 多谢啦！！

**Comment by shuangqiao999** [comment]
现在群里训练的已经超越了官方权重 群友有台双路志强铂金120线程的机器 跑谱很快 就是没有生成nnue的显卡 每次在云端学习 云端有文件大小的限制 每次跑谱不能超过4亿 我们能不能合作 我们跑谱把文件发给你 你在本地机器生成nnue文件？

**Comment by PikaCat-OuO** [comment]
> 现在群里训练的已经超越了官方权重 群友有台双路志强铂金120线程的机器 跑谱很快 就是没有生成nnue的显卡 每次在云端学习 云端有文件大小的限制 每次跑谱不能超过4亿 我们能不能合作 我们跑谱把文件发给你 你在本地机器生成nnue文件？

首先我很乐意帮助您，您是指您已经完成了训练流程是么？如果是这样的话，您应该可以在/logs/default(有的时候是lightning_logs)/version_0（也可能是version_1等，但是应该选取最大的version）/checkpoints文件夹下找到last.ckpt这个检查点文件，如果找到的话可以将它发给我，我可以将其转换为NNUE文件，那样就可以直接提交给官方了。 如下：
<img width="225" alt="image" src="https://user-images.githubusercontent.com/73384062/173226645-894188fc-daa0-4710-829b-a2ca732ea545.png">


其实这个转换也蛮简单的就是了
```bash
python serialize.py logs/default/version_0/checkpoints/last.ckpt xiangqi.nnue
```

**Comment by shuangqiao999** [comment]
nnue文件群友已经在云端生成了 就是想加大单次跑谱的数量 比如一次跑10亿 但是生成的.bin文件很大 云端限制 当前每次跑谱控制在3亿以内 群友想跑10亿的 期许能有大幅提升 因为云端限制 自己没有显卡 你生成的nnue文件是在云端还是自己的设备？如果你有设备 我们能不能把.bin文件发给你 由你生成nnue ？

**Comment by PikaCat-OuO** [comment]
我还以为您训练完了无法生成NNUE文件呢，误会了。。。
如果要跑10亿的话感觉至少需要七八十G的内存，我是学生党，没高级设备呀〒▽〒（第一次回答您的时候就已经有所体现了："我的机器性能不佳"），只能用云端的服务，Google Colab内存大约13G，Kaggle内存大约18G，达不到要求。。。

**Comment by shuangqiao999** [comment]
我们也是因为设备限制

**Comment by PikaCat-OuO** [comment]
但是根据https://github.com/ianfab/Fairy-Stockfish/discussions/491 中[Belzedar94](https://github.com/Belzedar94)的回答，我认为他应该可以做到，或许你们可以寻求他的帮助。
<img width="656" alt="image" src="https://user-images.githubusercontent.com/73384062/173228099-87dc583a-bec6-4c83-b3a0-025454942c68.png">

**Comment by shuangqiao999** [comment]
好的 谢谢你的建议

**Comment by PikaCat-OuO** [comment]
不客气，谢谢您的提问，我这种学生党没啥钱就只能白嫖Colab跑跑谱了😂。

**Comment by PikaCat-OuO** [comment]
您好，我咨询了一下我大数据的同学，他和我说在数据集足够大，样本足够均匀的情况下，10亿的训练集一起跑400个epoch和拆分成4亿跑400个epoch，3亿再跑400个epoch，3亿再跑400个epoch效果上来说不会相差很多。
从象棋数据集上看，已经上亿了，样本是足够大的，并且各种盘面都有包含在其中，样本也足够均匀，学习的方向也是一致的，从理论效果上来说不会相差很远（差距很小）。
另外，如果有什么问题的话也可以尽管问，在我的知识水平可以回答的范围我都会尽力为您解答的，可以在[Discussions](https://github.com/PikaCat-OuO/ChineseChess/discussions)中提问。
我考虑了一下，如果真的实在需要我加群的话我也可以加，如果你们愿意收留我的话( '◡' )（虽然说我看起来好像并不能帮上什么忙的样子(>︿<)）。
话说，前段时间尝试去搜索那个QQ群号发现搜不出来hh。

**Comment by PikaCat-OuO** [comment]
关于数据集拆开来训练这个问题过两天我也会顺带问一下fairy-stockfish的作者ianfab，了解一下他的观点。

**Comment by shuangqiao999** [comment]
现在群里训练了一个nnue文件 9层2.5亿 棋力比官方的高了大约12elo分数 等下我把那个nnue发给你 我会把你的建议反馈到群里 谢谢你的指导

**Comment by shuangqiao999** [comment]
发邮件被判定为垃圾邮件 文件不能被发送

**Comment by shuangqiao999** [comment]
现在群号可以被搜索到了  QQ群：615587792

**Comment by shuangqiao999** [comment]
期望你的加入

**Comment by shuangqiao999** [comment]
![1a1552fe53eb4fc5.jpg](https://user-images.githubusercontent.com/94234866/173529975-dae3ed92-6eaf-4410-aa09-380873dc52e9.jpg)
引擎是群友用仙女鱼代码编译的 修改了一些代码 棋力比官方发布的要好

**Comment by shuangqiao999** [comment]
你好 有没有计划写一个独立的中国象棋引擎？ 或者用SF15改编为中象引擎？
